"""relation troubles between roles and user

Revision ID: 771fb94009d4
Revises: 61dd55a06a19
Create Date: 2025-04-05 18:58:43.698860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '771fb94009d4'
down_revision: Union[str, None] = '61dd55a06a19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_uuid', sa.UUID(as_uuid=150), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_uuid')
    # ### end Alembic commands ###