"""Creación de tablas

Revision ID: cc8cb2a01933
Revises: 771fb94009d4
Create Date: 2025-04-24 18:05:01.733397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc8cb2a01933'
down_revision: Union[str, None] = '771fb94009d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_uuid', table_name='posts')
    op.drop_table('posts')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.create_table('posts',
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('desc', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('img', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uuid', name='posts_pkey')
    )
    op.create_index('ix_posts_uuid', 'posts', ['uuid'], unique=False)
    # ### end Alembic commands ###