"""Tablas Roles y User

Revision ID: fb512b9100b6
Revises: 18a9f091a715
Create Date: 2025-04-05 18:27:42.590043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb512b9100b6'
down_revision: Union[str, None] = '18a9f091a715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_session',
    sa.Column('uuid', sa.UUID(as_uuid=150), nullable=False),
    sa.Column('user_uuid', sa.UUID(as_uuid=200), nullable=True),
    sa.Column('token', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_user_session_uuid'), 'user_session', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_session_uuid'), table_name='user_session')
    op.drop_table('user_session')
    # ### end Alembic commands ###